[workspace]
resolver = "3"
members = [
  "crates/geo-sqlite",
  "crates/http-download",
  "crates/map",
  "crates/polyline-codec",
  "crates/polyline-simplify",
  "crates/tag-classify",
]

[workspace.dependencies]
geo-sqlite = { path = "crates/geo-sqlite" }
http-download = { path = "crates/http-download" }
polyline-codec = { path = "crates/polyline-codec" }
polyline-simplify = { path = "crates/polyline-simplify" }
rusqlite = { version = "0.40.2", features = ["bundled"] }
tag-classify = { path = "crates/tag-classify" }
tempfile = "3"
ureq = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT"

[workspace.lints.rust]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
